# SPDX-FileCopyrightText: 2025 ayangweb
# SPDX-FileCopyrightText: 2026 InfinityXCat
# SPDX-License-Identifier: MIT AND PolyForm-Noncommercial-1.0.0

name: MochiPaw Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-app:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install rust target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: target

      - name: Setup node with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install front-end dependencies
        run: |
          pnpm config set registry https://registry.npmjs.org
          pnpm install --no-frozen-lockfile

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          CI: false
          PLATFORM: windows-latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: MochiPaw ${{ github.ref_name }}
          releaseBody: ''
          releaseDraft: true
          prerelease: false
          args: --target x86_64-pc-windows-msvc --bundles msi

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: MochiPaw-msi-x86_64
          path: target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
          if-no-files-found: error
